# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/116cCb8L3-oOnNGhquSyfh2ZAAxo1A7tZ
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df = sns.load_dataset("tips")
pd.set_option("display.max_column", None)
pd.set_option("display.width", 500)
print(df.describe().T)
print(df.info())
print(df.head())

sns.boxplot(x ='tip', y ='day', data = df)
plt.show()

sns.scatterplot(x="total_bill", y="tip", data=df)
plt.show()


sns.violinplot(x ='time', y ='total_bill', hue='smoker',  data = df)
plt.show()


sns.barplot(x = 'sex', y = 'tip', hue = 'total_bill', data = df)
plt.show()


cat_col = [col for col in df.columns if str(df[col].dtypes) in ["category", "object", "bool"]]

print(cat_col)

num_but_cat = [col for col in df.columns if df[col].nunique() < 10 and df[col].dtypes in ["float64", "int64"]]

print(num_but_cat)

cat_cols = cat_col + num_but_cat




# Sayısal değişken Analizi

num_col = [col for col in df.columns if df[col].dtypes in ["int64", "float64"]]

print(num_col)

num_cols = [col for col in num_col if col not in cat_cols]

print(num_cols)

print(df.isnull().sum())


df_table = df["total_bill"]


q1 = df_table.quantile(0.25)
q2 = df_table.quantile(0.50)
q3 = df_table.quantile(0.75)

IQR = q3 - q1
print("Q1", q1)
print("Q3", q3)
print("IQR", IQR)

low_level = q1 - 1.5 * IQR
high_level = q3 + 1.5 * IQR

print("ALT SINIR :", low_level)
print("ÜST SINIR :", high_level)

aykirilar = ((df_table < low_level) | (df_table > high_level))

print("Aykırılar total_bill", aykirilar)
print(df_table[aykirilar])

print(df_table[aykirilar].index)

sns.boxplot(df["total_bill"])
plt.show()


df_table2 = df["tip"]


q1 = df_table2.quantile(0.25)
q2 = df_table2.quantile(0.50)
q3 = df_table2.quantile(0.75)

IQR = q3 - q1
print("Q1", q1)
print("Q3", q3)
print("IQR", IQR)

low_level = q1 - 1.5 * IQR
high_level = q3 + 1.5 * IQR

print("ALT SINIR :", low_level)
print("ÜST SINIR :", high_level)

aykirilar = ((df_table2 < low_level) | (df_table2 > high_level))

print("Aykırılar tip", aykirilar)
print(df_table2[aykirilar])

print(df_table2[aykirilar].index)

sns.boxplot(df["tip"])
plt.show()

"""Q1 2.0
Q3 3.5625
IQR 1.5625
ALT SINIR : -0.34375
ÜST SINIR : 5.90625
bu tip için değerlerimiz

Korelasyon, olasılık kuramı ve istatistikte iki rassal değişken arasındaki doğrusal ilişkinin yönünü ve gücünü belirtir. Genel istatistiksel kullanımda korelasyon, bağımsızlık durumundan ne kadar uzaklaşıldığını gösterir. bu nedenle veri setleri için analiz yaparken bu kurama göre ilerlersek daha iyi bir analiz yaparız.

Q1 13.3475
Q3 24.127499999999998
IQR 10.779999999999998
ALT SINIR : -2.8224999999999945
ÜST SINIR : 40.29749999999999
bu total bill için değerlerimiz

bu datasetinde verilerde hiç boşluk yoktur

Katogorik değişkenler:['sex', 'smoker', 'day', 'time', 'size']
Sayısal değişkenler: ['total_bill', 'tip']
olarak gözlemleye biliriz

Erkeklerin kadınlara göre daha fazla bahşiş bıraktığı görülüyor.

#En yüksek hesap ödeyenler akşam yemeğinde sigara içmeyen kesim olarak gözüküyor,öğle yemeğinde ise bu dağılım neredeyse sigara içen ve içmeyenler eşit olarak gözüküyor.

#En yüksek ortalamaya sahip ve çesitliliğe sahip gün pazar günüdür

#En yüksek hesapta en yüksek bahşiş bırakılmış, genel olarak hesap ne kadar düşük ise bahşiş de o kadar az oluyor.
"""